name: php7

on:
  push:
    branches:
      - master

env:
  REPOSITORY: jav13r/php

jobs:

  push_to_registry:
    name: Publish image docker hub
    runs-on: ubuntu-latest

    steps:
      - name: 10-Check out the repo
        uses: actions/checkout@v2

      - name: 20-Push image php7 cli
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          dockerfile: php/Dockerfile.php7-cli
          tags: 7.4-cli

      - name: 30-Push image php7 fpm
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          dockerfile: php/Dockerfile.php7-fpm
          tags: 7.4-fpm

      - name: 40-Push update README
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.REPOSITORY }}
          README_FILEPATH: ./php/README.md
