name: php5-cli

on:
  push:
    branches:
      - master

env:
  REPOSITORY: jav13r/php
  TAGS: "5.6-cli, 5.6.35-cli"
  DOCKERFILE_NAME: Dockerfile.php5-cli

jobs:

  push_to_registry:
    name: Publish image docker hub
    runs-on: ubuntu-latest

    steps:
      - name: 10-Check out the repo
        uses: actions/checkout@v2

      - name: 20-Push image to docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
          dockerfile: php/${{ env.DOCKERFILE_NAME }}
          tags: ${{ env.TAGS }}

      - name: 30-Push update README Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ env.REPOSITORY }}
          README_FILEPATH: ./php/README.md
